export { default as Home } from './Home' 
export { default as Leads } from './Leads' 
export { default as Login } from './login' 
export { default as Profile } from './Profile' 
export { default as Registration } from './Registration' 