export {default as FormComponent} from './FormComponent'
export * from './Bannerimage'
export * from './Logo'
export * from './StyledButton'
export * from './StyledInput'
export * from './Typographies'